page/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index), #Home page/
    path('contact', views.contact), #Home page/
]

studentManage/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('page.urls')),
    path('sinhvien/', include('students.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

students/urls.py
from os import name
from students.converters import FourDigitYearConverter
from django.urls import path, register_converter

from . import views

register_converter(FourDigitYearConverter, 'batky')

app_name = 'student'
urlpatterns = [
    path('', views.index, name='index'), #students/
    path('<int:student_id>', views.show, name='show'), #students/
    path('get-by-name/<slug:duongDan>/<int:student_id>', views.showBySlug, name='show-by-slug'), #students/
    path('class/<int:id>/students/name/<str:name>', views.getStudentByClass, name='student-in-class'), #students/
    path('search-by-year/<batky:year>', views.getStudentByYear, name='student-in-class-by-year'), #students/
    path('search-by-year/<str:name>', views.getStudentByName, name='student-in-class-by-name'), #students/
    path('welcome', views.welcome, name='welcome'), #students/welcome
    path('export', views.export, name='export'), #students/welcome
    path('test-form', views.testForm), #Home page/
    path('test-form-edit/<int:id>', views.testFormEdit), #Home page/
    path('test-session', views.testSession), #Home page/
    path('form-giai-pt-b2', views.giaiPtB2), #Home page/
    path('add-to-cart', views.addToCart), #Home page/
    path('cart', views.viewCart, name="cart"), #Home page/
    path('clear-cart', views.clearCart), #Home page/
    path('delete-cart-item/<int:product_id>', views.deleteCartItem, name="delete-cart-item"), #Home page/
    path('update-quantity/<int:product_id>', views.updateQuantity, name="update-cart-item"), #Home page/
    path('show-form-name', views.showFormName),
    path('checkout', views.checkout, name="checkout"),
    path('checkout-success', views.checkoutSuccess, name="checkout-success"),
    path('products', views.showProducts, name="product-index"),
    path('logout', views.logoutUser, name="logout"),
]
# "checkout-success" => "http://127.0.0.1:8000/sinhvien/checkout-success"

# /student/7

# <a href="/student/chi-tiet/id">Chi tiet sinh vien</a>
# <a href="/student/chi-tiet/id">Chi tiet sinh vien</a>
# <a href="/student/chi-tiet/id">Chi tiet sinh vien</a>

students/models.py
import students
from django.db import models
from django.contrib import admin
from django.db.models.base import Model
from django.urls import reverse


class ClassModel(models.Model):
    name = models.CharField(max_length=200)
    teacher_name = models.CharField(max_length=200)

    def __str__(self) -> str:
        return self.name


class GenderChoices(models.IntegerChoices):
    S = 0, 'Nữ'
    F = 1, 'Nam'
    U = 2, 'Không xác định'

class Skill(models.Model):
    name = models.CharField(max_length=255)
    def __str__(self) -> str:
        return self.name


class Subject(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.name

class Profile(models.Model):
    id_code = models.CharField(null=True, max_length=255, unique=True)
    dob = models.DateField(null=True)
    phone = models.CharField(null=True, max_length=255)

    def __str__(self):
        return self.id_code + str(self.dob) + self.phone

class Student(models.Model):
    class Meta:
        permissions = [
            ("change_task_status", "Can change the status of tasks"),
            ("close_task", "Can remove a task by setting its status as closed"),
            ("grade_latest_exam_score", "Cập nhật điểm đồ án tốt nghiệp"),
        ]
    id = models.BigAutoField(primary_key=True)
    class_model = models.ForeignKey(ClassModel, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=200, help_text="Tên sinh viên, ví dụ:  Nguyễn Văn A")
    gender = models.IntegerField(choices=GenderChoices.choices)
    address = models.TextField()
    student_code = models.CharField(max_length=200)
    is_paid = models.BooleanField(default=False)
    go_to_school_at = models.DateField(null=True)
    skills = models.ManyToManyField(Skill, verbose_name="Danh sách Kỹ năng")
    subjects = models.ManyToManyField(Subject, through='SubjectRegistration')
    profile = models.OneToOneField(Profile, on_delete=models.CASCADE, null=True)
    @admin.display(
        boolean=True,
        description='Đã thanh toán?',
    )
    def isPaid(self):
        return self.is_paid

    def get_absolute_url(self):
        student_id = self.id
        return reverse('student:show', args=(student_id,))

    @admin.display(
        description='Giới tính',
    )
    def genderStr(self):
        return self.get_gender_display()
    #anotation
    @admin.display(
        description='Kỹ năng',
    )
    def skillStr(self):
        if self.skills.count() > 0:
            skills = []
            for skill in self.skills.all():
                skills.append(str(skill))
            return ", ".join(skills)
        else:
            return "Không có kỹ năng"


    def __str__(self) -> str:
        return self.name

class SubjectRegistration(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, verbose_name="Sinh viên")
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, verbose_name="Môn học")
    reg_at = models.DateField(null=True, verbose_name="Ngày đăng ký")
    score = models.FloatField(default=0, verbose_name="Điểm trung bình")

    def __str__(self):
        return str(self.student) + " - " + str(self.subject)


class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.FloatField(default=0)
    image = models.ImageField(upload_to="products")

    def __str__(self):
        return "[" + str(self.id) + "] " + self.name


class Order(models.Model):
    def __str__(self) -> str:
        return self.customer_name

    customer_name = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    phone = models.CharField(max_length=255)
    total = models.IntegerField(default=0)

class OrderDetail(models.Model):
    product = models.ForeignKey(Product, verbose_name="Sản phẩm", on_delete=models.CASCADE)
    price = models.FloatField(default=0)
    quantity = models.IntegerField(default=1)
    order = models.ForeignKey(Order, verbose_name="Đơn hàng", on_delete=models.CASCADE)

students/views.py
from django.contrib.auth.decorators import login_required, permission_required
import students
from students.form import CheckoutForm, RandomForm, StudentForm, GiaiPTB2Form, NameForm
from django.http.response import Http404, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.http import HttpResponse
from .models import Order, OrderDetail, Product, Student, SubjectRegistration
from django.template.defaultfilters import slugify
from django.urls import reverse
import csv
import logging
from django.contrib.auth import logout

# Get an instance of a logger
logger = logging.getLogger(__name__)

@login_required(login_url="/admin/login/", redirect_field_name="chuyen_huong")
def index(request):
    if (request.user.is_authenticated):
        print(request.user.username)
        print(request.user.email)
    else:
        print('User is not login')



    hoten  = request.POST.get('hoten', '')
    students = Student.objects.filter(name__icontains=hoten)
    data = {
        'students': students,
        'hoten': hoten,
        'genderMeta': {
            1: "Nam",
            2: "Nữ",
        }
    }

    return render(request, 'students/index.html', data)

def show(request, student_id):

    try:
        student = Student.objects.get(pk=student_id)
    except Student.DoesNotExist:
        raise Http404("Sinh viên không tồn tại")
    subjectRegistrations = SubjectRegistration.objects.filter(student=student)
    slugGenerate = slugify(student.name)
    print(slugGenerate)
    data = {
        "student": student,
        "subjectRegistrations": subjectRegistrations,
    }
    print(subjectRegistrations)
    return render(request, 'students/show.html', data)

def showBySlug(request, duongDan, student_id):
    # print(slug)
    student = Student.objects.get(pk=student_id)
    subjectRegistrations = SubjectRegistration.objects.filter(student=student)
    slugGenerate = slugify(student.name)
    print(slugGenerate)
    data = {
        "student": student,
        "subjectRegistrations": subjectRegistrations,
    }
    print(subjectRegistrations)
    return render(request, 'students/show.html', data)

def getStudentByClass(request, id, name):
    print(id)
    print(name)

    return HttpResponse("Danh sách sinh viên của lớp có id " + str(id) + " có tên " + name)
    # return render(request, 'students/show.html', data)

def getStudentByYear(request, year):
    print(year)

    return HttpResponse("Danh sách sinh viên của có năm sinh" + str(year))
    # return render(request, 'students/show.html', data)

def getStudentByName(request, name):

    return HttpResponse("Danh sách sinh viên có tên " + name)
    # return render(request, 'students/show.html', data)

def welcome(request):
    # Solution 1
    # std = Student.objects.get(pk=1)
    # return redirect(std)

    # Solution 2
    return redirect(reverse('student:show', args=(10,)))


    # Solution 3
    return redirect("https://google.com")

    year = 1995
    url = reverse('student:student-in-class-by-year', args=(year,))
    name = "Quyet Quyet2"
    url = reverse('student:student-in-class-by-name', args=(name,))
    return HttpResponse(url)



def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip

def export(request):
    response = HttpResponse(
        content_type='text/csv',
        headers={'Content-Disposition': 'attachment; filename="students.csv"'},
    )

    writer = csv.writer(response)
    students = Student.objects.all()
    for std in students:
        writer.writerow([std.id, std.name, std.gender, std.address])

    # return

def testForm(request):
    f = StudentForm()

    if request.method == "POST":
        f = StudentForm(request.POST)
        if f.is_valid():
            f.save()
            return HttpResponse('Success')
    else:
        f = StudentForm()

    response = render(request, 'students/test-form.html', {"f": f})
    return response

def testFormEdit(request, id):
    f = StudentForm()
    students = Student.objects.get(pk=id)
    print(students)
    # print(request.session.items())
    if request.method == "POST":
        f = StudentForm(request.POST, instance= students)
        print(f.errors.as_data().get("1221"))
        if f.is_valid():
            f.save()
            return HttpResponse('Success')
    else:
        f = StudentForm(instance=students)


    response = render(request, 'students/test-form.html', {"f": f})
    return response


def testSession(request):
    # print(request.COOKIES)
    request.session['cart'] = [
        {
            "name" : "Iphone 12",
            "price": 1000,
            "quantity": 2
        }
    ]

    return HttpResponse("Test Session")


def addToCart(request):
    # print(request.COOKIES)
    product = Product.objects.get(pk=2)
    cart = []
    if "cart" in request.session:
        cart = request.session['cart']
    updatedCart = []
    inCart = False
    for cartProduct in cart:
        currentId = cartProduct.get('id')
        if currentId == product.id:
            inCart = True
            cartProduct['quantity'] = cartProduct['quantity'] + 1
        updatedCart.append(cartProduct)

    if inCart == False:
        updatedCart.append({
            'id': product.id,
            'name': product.name,
            'price': product.price,
            'quantity': 1,
        })

    request.session['cart'] = updatedCart

    # return HttpResponse('Add to cart')
    return HttpResponseRedirect('/sinhvien/cart')

def clearCart(request):
    del request.session['cart']
    return HttpResponse("Xóa sạch giỏ hàng")

def updateQuantity(request, product_id):
    # del request.session['cart']
    quantity = request.POST['quantity']


    product = Product.objects.get(pk=product_id)
    cart = []
    if "cart" in request.session:
        cart = request.session['cart']
    updatedCart = []
    inCart = False
    for cartProduct in cart:
        currentId = cartProduct.get('id')
        if currentId == product.id:
            inCart = True
            cartProduct['quantity'] = quantity
        updatedCart.append(cartProduct)

    if inCart == False:
        updatedCart.append({
            'id': product.id,
            'name': product.name,
            'price': product.price,
            'quantity': product_id,
        })


    request.session['cart'] = updatedCart
    return HttpResponseRedirect('/sinhvien/cart')

    # return HttpResponse("Cập nhật số lượng giỏ hàng")

def viewCart(request):
    cart = None
    if "cart" in request.session:
        cart = request.session['cart']
    print(cart)
    return render(request, 'cart.html', {"cart": cart})

def deleteCartItem(request, product_id):

    cart = []
    if "cart" in request.session:
        cart = request.session['cart']
    updatedCart = []
    for cartProduct in cart:
        currentId = cartProduct.get('id')
        if currentId != product_id:
            updatedCart.append(cartProduct)

    request.session['cart'] = updatedCart

    return HttpResponseRedirect('/sinhvien/cart')

    # return HttpResponse("Xóa sản phẩm trong giỏ hàng")



def giaiPtB2(request):
    f = GiaiPTB2Form()
    if request.method == "POST":
        f = GiaiPTB2Form(request.POST)
        if f.is_valid():
            a = f.cleaned_data.get("a")
            b = f.cleaned_data.get("b")
            c = f.cleaned_data.get("c")
            print(a)
            print(b)
            print(c)
    return render(request, 'students/test-form.html', {
        'f': f
    })


def showFormName(request):
    form = NameForm()
    if request.method == "POST":
        # c1
        # name = request.POST.get("name")
        # return HttpResponse("Hello" + name)

        # c2
        form = NameForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data.get("name")
            address = form.cleaned_data.get("address")
            return HttpResponse("Hello:" + name + " Address:" + address)
        else:
            for field in form.errors:
                form[field].field.widget.attrs['class'] += ' is-invalid'


    return render(request, 'form-demo.html', {'form': form})

# (login_url='/admin/login/')
# @login_required(login_url='/admin/login/')
def checkout(request):
    form = CheckoutForm()
    cart = None
    total = 0
    if "cart" in request.session:
        cart = request.session['cart']
        for cartProduct in cart:
            print(cartProduct.get('price'))
            total = total + int(cartProduct.get('price')) * int(cartProduct.get('quantity'))
    else:
        print("Hello")
        return redirect('student:cart')
    # print(total)


    if request.method == "POST":
        form = CheckoutForm(request.POST)
        if form.is_valid():
            customer_name = form.cleaned_data['customer_name']
            address = form.cleaned_data['address']
            phone = form.cleaned_data['phone']

            order = Order(
                customer_name = customer_name,
                address = address,
                phone = phone,
                total = total
            )
            order.save()

            for cartProduct in cart:
                print(cartProduct.get("id"))
                product = Product.objects.get(pk=cartProduct.get("id"))
                quantity = cartProduct.get('quantity')
                price = cartProduct.get('price')
                OrderDetail.objects.create(
                    order = order,
                    product = product,
                    quantity = quantity,
                    price = price,
                )
            # return redirect('student:checkout-success')
            return HttpResponseRedirect(reverse('student:checkout-success'))

    return render(request, 'checkout.html', {'form': form, "cart": cart, "total": total})

def checkoutSuccess(request):

students/templates/cart.html
{% extends 'students/base.html' %}

{% block content %}
  <h1>
    Giỏ hàng
  </h1>
  {% if cart %}
    {% for product in cart %}

      <div class="row">
        <div class="col-md-8">
          <p>
            <strong>
              {{ product.name }}
            </strong>
          </p>
          <p>
            {{ product.price }} $
          </p>
        </div>
        <div class="col-md-4">
          <a href="{% url 'student:delete-cart-item' product.id %}" >
            Delete
          </a>
          <form class="form-update-quantity" action="{% url 'student:update-cart-item' product.id %}" method="POST">
            {% csrf_token %}
            <input name="quantity" class="quantity" type="number" value="{{ product.quantity }}">
            <button class="btn btn-default" type="submit">
              Cập nhật
            </button>
          </form>
        </div>
      </div>
    {% endfor %}
    <a href="{% url 'student:checkout' %}">Đi đến thanh toán</a>


  {% else %}

    <p>Chưa có sản phẩm nào trong giỏ hàng</p>
  {% endif %}
{% endblock content %}
{% block footer %}
  <script>
    $(document).ready(function () {
      $(".form-update-quantity").submit(function (event) {
        event.preventDefault();
        let url = $(this).attr('action')
        let quantity = $(this).find(".quantity").val()
        console.log(url)
        console.log(quantity)
        let csrf_token = $(this).find("input[name=csrfmiddlewaretoken]").val()

        $.ajax({
          method: 'POST',
          url: url,
          data: {
            csrfmiddlewaretoken: csrf_token,
            quantity: quantity
          },
          success: function(result){
             toastr.success('Thông báo', 'Cập nhật giỏ hàng thành công')
          }
        });
      })
    });
  </script>
{% endblock footer %}

students/templates/checkout-success.html
{% extends 'students/base.html' %} {% block content %} {% load mathfilters %}
<div class="row">
  <div class="col-md-6">
    <h1>Thanh toán thành công</h1>
    <p>Chúng tôi sẽ liên hệ với bạn sớm để xác nhận đơn hàng</p>
</div>

{% endblock content %}

students/templates/checkout.html
{% extends 'students/base.html' %} {% block content %} {% load mathfilters %}
<div class="row">
  <div class="col-md-6">
    <h1>Checkout</h1>
    {% if cart %}
    <h4>Thông tin sản phẩm có trong giỏ hàng</h4>
    <table class="table">
      <tr>
        <th>Tên sản phẩm</th>
        <th>Giá sản phẩm</th>
        <th>Số lượng</th>
        <th>Thành tiền</th>
      </tr>
      {% for product in cart %}
      <tr>
        <td>
          <strong> {{ product.name }} </strong>
        </td>
        <td>
          <p>{{ product.price }} $</p>
        </td>
        <td>
          <p>{{ product.quantity }}</p>
        </td>
        <td>
          <p>{{ product.quantity|mul:product.price }} $</p>
        </td>
      </tr>
      {% endfor %}

    </table>
    <p>
      Tổng thanh toán: {{ total }} $
    </p>
    {% else %}

    <p>Chưa có sản phẩm nào trong giỏ hàng</p>
    {% endif %}
  </div>

  <div class="col-md-6">
    <form action="" method="POST" novalidate>
      {% csrf_token %} {{ form }}
      <div class="mt-5">
        <button class="btn btn-primary">Đặt hàng</button>
      </div>
    </form>
  </div>
</div>

{% endblock content %}

students/templates/form-demo.html
{% extends 'students/base.html' %}
{% block content %}

<div class="row">
  <div class="col-md-6">

      <form action="" method="POST" novalidate>
        {% csrf_token %}

      <div class="form-group">
        <label for="exampleInputEmail1">Nhập họ tên</label>
          {{form.name}}
        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        <div class="invalid-feedback">
          {{ form.name.errors }}
        </div>
      </div>

      <div class="form-group">
        <label for="exampleInputEmail1">Nhập Email</label>
        {{ form.email }}
        <div class="invalid-feedback">
          {{ form.email.errors }}
        </div>
      </div>
        <div>
          <button class="btn btn-primary">Get Name</button>
        </div>
      </form>
    </div>
  </div>

{% endblock content %}